### ISSUE TITLE
Version 1.1.0 of guice-extension breaks parameterized tests.

### ISSUE THREAD

**Issue by SergeyAlekseevN** [JeffreyFalgout/junit5-extensions#4]
After updating Guice-Extension to the new version, the parameterized tests broke down.
```java
@ExtendWith(GuiceExtension.class)
public class Test {
    @ParameterizedTest
    @ValueSource(strings = {"one", "two", "three"})
    void test(String count) {
        assertTrue(true);
    }
}
```

Error:
```java
org.junit.jupiter.api.extension.ParameterResolutionException: Discovered multiple competing ParameterResolvers for parameter [java.lang.String arg0] in method [void com.tests.Test.test(java.lang.String)]: name.falgout.jeffrey.testing.junit.guice.GuiceExtension@19e4653c, org.junit.jupiter.params.ParameterizedTestParameterResolver@795509d9
```

I researched this problem and found that the reason is built-in binding for String.class.
String has empty constructor and binds in runtime by Guice to "" (empty string).

See line 206:
https://github.com/JeffreyFalgout/junit5-extensions/commit/adf2f4ece977e834ba9b4f1563ebc568784ad3a4#diff-5eef6748419687f2efdf650d6649f118

I suggest to add additional annotation with bindingModeParam(ALL,EXPLICIT_ONLY) to set binding mode and process it in `supportsParameter` method.

..or just make workaround with built-in binding String.class.

I would like to hear your opinion and suggestions on this issue.

**Comment by JeffreyFalgout** [comment]
Nice find. Explicit only is probably a non-starter, because a lot of people rely on implicit just-in-time bindings for their `@Inject` annotated classes.

Special casing `String` to be explicit only makes sense, though. If you want to take a crack at it, I'd be happy to take a PR. Otherwise I'll probably get around to this in the next couple of weeks
